spring:
  application:
    name: msc-itr
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: msc-itr
    res:
      defaultMediaType: application/json

server:
  port: 8085
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

swagger:
  version: 1.0
  description : APIs STUR ITR